### ISSUE TITLE
JohnOlutubo: Workflows-bio, 2weeks

### ISSUE THREAD

**Issue by JohnOlutubo** [HYF-Class19/home#107]
> [my fork of module repository]()

**Comment by yildiztugba** [comment]
hi @JohnOlutubo, We are creating different issues for check in and deliverable. this is your deliverable issue linked with your pull request. thats why it was closed automatically after I merged it.

You should  create new issue with check in template and copy paste your questions&answers.

**Comment by yildiztugba** [comment]
oh you did mixed them, i think. okay, i will reopen and review this as your check in. Next time, please create different issues.

**Comment by yildiztugba** [comment]
@JohnOlutubo if you want to overview of the steps, I wrote the steps that we did for student bio task, you can check it out #120 

> Wrapping my head around the step-by-step approach to the workflow using CLI.

**Comment by JohnOlutubo** [comment]
# Week 2  
I have pushed my progress to [workflow-group-3](https://github.com/HYF-Class19/workflow-group-3)

## I need Help With:
No need for help so far. Thanks to our coaches, and my group members.

## What went well?
There was a pretty good teamwork and collaboration.

## What went less well?
- I struggled a little with synchronizing my local repo with the remote.
- It was a tough one realizing I had to rename my `md file` into lowercase after creating a pull request.
- My workflow was disrupted in the attempt to make corrections, and I had to start all over.

## Lessons Learned
- I now have a better grasp of the npm and Json packages, and dependencies.
- I also learned that it is a good practice to use git status often to check the state of work and also to commit very often.
- I am getting more familiar and comfortable with the CLI.

## Sunday Prep Work
I started reading on [Agile Development ](https://github.com/hackyourfuturebelgium/agile-development), and I will continue to practice [HTML & CSS](https://github.com/HackYourFutureBelgium/template-html-css).
