### ISSUE TITLE
Valeriya: Workflows, 2 week

### ISSUE THREAD

**Issue by V-Valkiriya** [HYF-Class19/home#149]
- Setup: GitHub
  - [x] created this issue
  - [x] assigned myself
  - [x] moved the issue to the project board
- Setup: local
  - [x] pulled the most recent code from `main`/`master`
  - [x] created a new branch for my introduction
- Writing the content:
  - [x] added my intro file in `/people` according to group conventions
  - [x] linked to my file from `/README.md` according to group conventions
- Before pushing my branch:
  - [x] formatted the code
  - [x] fixed all spelling mistakes and added new words to the dictionary
  - [x] fixed all linting mistakes
- After pushing my branch:
  - [x] created a new PR linked to this issue
  - [ ] make sure all of the checks passed
  - [ ] assigned someone to review and merge my PR

**Comment by talmurshidi** [comment]
Please close this issue and create a new one inside your group's repo.
