### ISSUE TITLE
ANASS ABBAR . PRE-COURSE. WEEK-1 

### ISSUE THREAD

**Issue by anasabbar** [HYF-Class19/home#51]
> [my fork of module repository]()

**Comment by yildiztugba** [comment]
Hi, @anasabbar You are supposed to add "checkin questions" and answer them. This was yesterday's task. Please do your task on time and finish your check-in. if you have trouble on something, please ask on Discord.

**Comment by anasabbar** [comment]
- **GitHub**:
  - [X] 🥚 **Creating Issues**: You can create a new issue in a GitHub repository using an issue template. You can correctly use labels, milestones, and assignment to make your issue findable.
  - [X] 🥚 **Searching Issues**: You can find issues in a repository by label, author, and milestone.
  - [X] 🥚 **Project Boards**: You can use issues on a GitHub project board to track your class assignments and help your classmates when they need it.
- **HYF Workflows**:
  - [X] 🥚 **Check-Ins**: You can use the `check-in` template to track your module learning objectives, your weekly progress (and to post a retrospective at the end of the module). You create one check-in issue per module in the class repo and each Thursday you add a check-in comment to it and the label for the corresponding week. After review, we add the checked label. No need to remove previous labels either. So as an example, after a 5 week module, you would have 5 comments and 5 labels added by you. 
  - [X] 🥚 **Deliverables**: You can create an issue for this module's `deliverable` and track your progress on the class project board. Each week, there are different assignments / deliverables. If it is an individual project, you create your own deliverable issue for it in the class repo. If it is a group project, the entire group creates 1 issue together in the class repo.
  - [X] 🥚 **Asking for Help**: You can use the `help-wanted` template in your class repository's Discussion board to ask for help, and to help your classmates when they are blocked.
- **Your Computer**:
  - [X] 🥚 **File System Management**: You can create and organize a new folder in your personal computer for the materials you will study at HYF.
- **Visual Studio Code**:
  - [X] 🥚 Install and manage extensions
  - [X] 🥚 Open a folder for editing
  - [X] 🥚 Create new files/folders inside of the folder
  - [X] 🥚 Edit files and save changes

**Comment by anasabbar** [comment]
# Week 1
- [X] I have pushed my progress to [my fork of exercises repo](https://github.com/HYF-Class19/home/issues/51)

## I Need Help with
I’m still confused about the issues . I found it very strange for me to use issues 
## What went well?
making issues and check-Ins, I learned to use vscode and i hope gonna learn more about it .
## What went less well?
putting questions in the template. I had to do many mistakes to make it work till I figured out what i have to do exactly.
## Lessons Learned
I learned that i have to do as many as i can of mistakes to make it work in the end .
## Sunday Prep Work
I will not be here for the lesson of this weekend, so I will prep next week
