### ISSUE TITLE
Valeriya: Workflows, student-bio, 2 week

### ISSUE THREAD

**Issue by V-Valkiriya** [HYF-Class19/home#81]
- [x] I wrote my markdown locally on a new branch
- [x] My bio file is named _exactly_ the same as my GitHub username
- [x] My `bio` link in the class README opens to my student bio file
- [x] I pulled and merged `main` into my branch before pushing
- [x] I pushed my branch to the class repository and opened a PR
- [x] I went through the PR checklist
- [x] All the CI check pass
- [x] I assigned a coach to review my PR
- [x] I
      [linked my PR to this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by talmurshidi** [comment]
Please write a descriptive issue's title that shows this issue for student-bio.
